branches:
  only:
    -develop
    
language: node_js

node_js:
  - "12.16.1"

cache:
  directories:
    - "node_modules"

install:
  - cd $TRAVIS_BUILD_DIR
  - npm install

script:
  - pwd
  - ls
  - npm run build

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: develop
  on:
    branch: develop
